apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: fleet-infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 60s
  url: ssh://git@github.com/Yacine8888/fleet-infra.git
  secretRef:
    name: flux-system
